### ISSUE TITLE
Frequent API access issues

### ISSUE THREAD

**Issue by gkronisch** [radeklat/todoist-habitica-sync#36] opened 2023-05-17 02:02 UTC
I keep getting the following error messages from the interface:
[ERROR]: Unexpected network error: 401 Client Error: Unauthorized for url: https://habitica.com/api/v3/tasks/[task ID?]/score/up
The Todoist API seems to be working fine, but the Habitica side is not syncing with the tool at all lately.

When I go to habitica.com/api, I get the following:
{"success":false,"error":"NotFound","message":"Not found."}

Please advise?

**Comment by radeklat** [comment] 2023-05-25 12:14
Hello @gkronisch. I'm sorry to hear about the sync not working. There might have been a change in the API. I'm on a vacation at the moment without a computer. So the earliest I can have a look is from 30 May onwards.

**Comment by gkronisch** [comment] 2023-05-28 04:35
N

**Comment by gkronisch** [comment] 2023-05-28 04:37
No worries @radeklat! Thank you for your reply. It seems to be working now. However, this issue recurs every now and then, seemingly at random, so it may be good to figure out what is causing it and whether that cause can be avoided.

**Comment by radeklat** [comment] 2023-11-13 15:15
@gkronisch My apologies for a late reply. I didn't manage to reproduce the issue until recently. It happened when a task in Habitica got deleted and the script tried to operate on it. The "Unauthorized" error message led me to believe it was due to authentication issues. It should be fixed in #42 Is this happens, the task will either get recreated if scoring it up is attempted or ignored if it was supposed to be deleted.

**Closed by radeklat** 2023-11-13 15:15 UTC
