### ISSUE TITLE
Rescheduling a recurring task completes it in Habitica

### ISSUE THREAD

**Issue by qfettes** [radeklat/todoist-habitica-sync#7] opened 2021-07-01 22:03 UTC
If a recurring task is rescheduled in todoist, the task is mistakenly marked as completed in Habitica.

It's possible this also affects non-recurring tasks, but I haven't tested it.

**Comment by radeklat** [comment] 2022-01-30 21:39
Recurring tasks were indeed awarded points only once (as reported in #4). This is fixed now. By design, all Todoist tasks are transformed into Habitica To Do's (not Dailies or Habits). Because this is a one way sync and finishing Dailies or Habits would not be reflected in Todoist. Any kind of Todoist task won't be visible in Habitica as it is remove immediately after creation.

**Closed by radeklat** 2022-01-30 21:39 UTC
